services:
    sonata.admin.braunedigital.translationbase.language:
        class: BrauneDigital\TranslationBaseBundle\Admin\LanguageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Escape Gamer", label: "Sprachen" }
        arguments:
            - ~
            - BrauneDigital\TranslationBaseBundle\Entity\Language
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationAppBundle]]